#user
api_me:
    path: '/api/me'
    methods: ['GET','PUT']
    defaults:
        _controller: App\Controller\UserController::meAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'me'
        
resetPassword:
    path: '/api/reset-password'
    methods: ['POST','GET']
    defaults:
        _controller: App\Controller\UserController::resetPasswordRequestAction

api_register:
    path: '/api/register'
    methods: ['POST']
    defaults:
        _controller: App\Controller\UserController::registerAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'register'
        
login:
    path: '/login'
profile:
    path: '/profile'
admin:
    path: '/admin'
