doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from Acme\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations': '%kernel.project_dir%/../../src/Delivery/Infrastructure/Shared/Migration'

  # available in version >= 1.2. Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: false
  enable_profiler: '%kernel.debug%'
  storage:
    # Default (SQL table) metadata storage configuration
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 1024
      executed_at_column_name: 'executed_at'
      execution_time_column_name: 'execution_time'
