resources:
    App\Entity\Bussines:
        attributes:
            normalization_context:
                groups: ['bussines-read']
            denormalization_context:
                groups: ['bussines-write']
        collectionOperations:
            get:
                method: 'GET'

            post:
                method: 'POST'

