resources:
    App\Entity\Plate:
        attributes:
            normalization_context:
                groups: ['plate-read']
            denormalization_context:
                groups: ['plate-write']
        collectionOperations:
            get:
                method: 'GET'

            post:
                method: 'POST'

